reviewers:
  defaults:
  - tniita
  - mmarukaw
  - shukawam

files:
  '_templates/**':
    - tniita
    - mmarukaw
    - oraryoyas
    - gakumura
    # - eminamin
    - TomokoKonishi
    - shukawam
    - kyyamada
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sesecho
    - yobaya
    - fwiw6430
    - kofukush
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '_posts/**':
    - tniita
    - mmarukaw
    - oraryoyas
    - gakumura
    # - eminamin
    - TomokoKonishi
    - shukawam
    - kyyamada
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sesecho
    - yobaya
    - fwiw6430
    - kofukush
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '_pages/**':
    - tniita
    - mmarukaw
    - oraryoyas
    - gakumura
    # - eminamin
    - TomokoKonishi
    - shukawam
    - kyyamada
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sesecho
    - yobaya
    - fwiw6430
    - kofukush
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '.github/**':
    - tniita
    - mmarukaw
    - shukawam

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3