reviewers:
  defaults:
  - tniita
  - mmarukaw
  - shukawam
  - cyberblack28
  - nonkyon

files:
  '_templates/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - kumasan368
    - gakumura
    - yoichiro0217
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - Kyohei-Git
    - snakane
    - taekohayashi
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sji-cho
    - sshatari
    - yobaya
    - fwiw6430
    - knagasue
    - fukuora
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '_posts/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - kumasan368
    - gakumura
    - yoichiro0217
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - Kyohei-Git
    - snakane
    - taekohayashi
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sji-cho
    - sshatari
    - yobaya
    - fwiw6430
    - knagasue
    - fukuora
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '_pages/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - kumasan368
    - gakumura
    - yoichiro0217
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - Kyohei-Git
    - snakane
    - taekohayashi
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sji-cho
    - sshatari
    - yobaya
    - fwiw6430
    - knagasue
    - fukuora
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '.github/**':
    - tniita
    - mmarukaw
    - shukawam
    - cyberblack28
    - nonkyon

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3