reviewers:
  defaults:
    - tniita
    - mmarukaw
    - shukawam

files:
  "_templates/**":
    - tniita
    - mmarukaw
    - gakumura
    - eminamin
    - TomokoKonishi
    - shukawam
    - kyyamada
    - yuarashi
    - ora-takahnak
    - s-nori
    - yuuur
    - fwiw6430
    - kofukush
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ntakei1
    - watarunS
    - unyako
    - t-utsunom
    - sogawa-yk
    - alkuma-san
  "_posts/**":
    - tniita
    - mmarukaw
    - gakumura
    - eminamin
    - TomokoKonishi
    - ora-takahnak
    - shukawam
    - kyyamada
    - yuarashi
    - s-nori
    - fwiw6430
    - kofukush
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ntakei1
    - watarunS
    - unyako
    - t-utsunom
    - sogawa-yk
    - alkuma-san
  "_pages/**":
    - tniita
    - mmarukaw
    - gakumura
    - eminamin
    - TomokoKonishi
    - shukawam
    - ora-takahnak
    - kyyamada
    - yuarashi
    - s-nori
    - fwiw6430
    - kofukush
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ntakei1
    - watarunS
    - unyako
    - t-utsunom
    - sogawa-yk
    - alkuma-san
  ".github/**":
    - tniita
    - mmarukaw
    - shukawam

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3
