apiVersion: v1
kind: Service
metadata:
  name: ocidocs-preview
  namespace: paasdocs-preview
spec:
  selector:
    app: ocidocs-preview
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocidocs-preview
  namespace: paasdocs-preview
  labels:
    app: ocidocs-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocidocs-preview
  template:
    metadata:
      labels:
        app: ocidocs-preview
    spec:
      containers:
      - name: ocidocs-preview
        image: nrt.ocir.io/orasejapan/oci-tutorials/staging-env-ocidocs:${BUILDRUN_HASH}
        ports:
        - protocol: TCP
          containerPort: 4001
      imagePullSecrets:
      - name: paasdocs-preview-image-pull-secret

