name: create pull request

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create pull request
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update the OCI Docs:${{ github.sha }}',
              body: 'Update the OCI Docs',
              head: 'develop',
              base: 'master'
            })