name: create pull request

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create pull request
        uses: actions/github-script@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update the OCI Docs:${{ github.sha }}',
              body: 'Update the OCI Docs',
              head: 'develop',
              base: 'master'
            })